CREATE DATABASE prueba_sync;
USE prueba_sync;

CREATE TABLE texts(
id INT PRIMARY KEY NOT NULL,
record VARCHAR(200) NOT NULL
);

/*nueva modificacion */
INSERT INTO texts VALUES(1, "HE AGREGADO EL PRIMER REGISTRO");
INSERT INTO texts VALUES(2, "HE AGREGADO EL SEGUNDO REGISTRO");